spring:
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shop
    username: postgres
    password: postgres
  liquibase:
    password: postgres
    user: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shop
    change-log: db/changelog/db.changelog-master.yaml
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
    path: /swagger-ui
