
services:
  database:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: store
    networks:
      - postgres-network
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d

networks:
  postgres-network:
    driver: bridge
